name: build-images

on:
  schedule:
    - cron: '0 4 * * *' # everyday at 4am
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          install: true

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get project version
        id: version
        uses: mikefarah/yq@v4
        with:
          cmd: yq --input-format xml .project.version pom.xml

      - name: Build images
        run: |
          docker build \
            --build-arg BUILD_DATE="$(date)" \
            --build-arg VCS_REF="${GITHUB_SHA}" \
            --build-arg VERSION="${{ steps.version.outputs.result }}" \
            --tag syphr/dash-listener:"${version}" \
            --tag syphr/dash-listener:latest \
            --platform linux/amd64,linux/arm64 \
            --push \
            .

      - name: Cleanup
        run: rm -f ${HOME}/.docker/config.json
