name: build-pr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          install: true

      - name: Get project version
        id: version
        uses: mikefarah/yq@master
        with:
          cmd: yq --input-format xml '.project.version' pom.xml

      - name: Build images
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          version="${{ steps.version.outputs.result }}"
          docker build \
            --build-arg BUILD_DATE="$(date)" \
            --build-arg VCS_REF="${GITHUB_SHA}" \
            --build-arg VERSION="${version}-PR.${PR_NUMBER}" \
            --platform linux/amd64,linux/arm64,linux/arm \
            .
